import { BotPlugin } from "./plugin";

/**
 * Response object returned after executing a bot conversation step.
 *
 * Contains the messages to send back to the user, information about
 * the next node to execute, and whether the conversation has ended.
 *
 * @example
 * ```typescript
 * const response: FlowResponse = {
 *   messages: ["Hello!", "How can I help you today?"],
 *   next: "main.menu",
 *   done: false
 * };
 *
 * // Terminal node response
 * const endResponse: FlowResponse = {
 *   messages: ["Goodbye!"],
 *   next: undefined,
 *   done: true
 * };
 * ```
 */
export type FlowResponse = {
  /**
   * Array of messages to send back to the user.
   * These messages are generated by calling the `send()` function
   * within node handlers and may be transformed by plugins.
   */
  messages: string[];

  /**
   * The next node to execute in subsequent bot runs.
   * - Contains the full node ID in "flow.node" format
   * - `undefined` when the conversation has ended (done = true)
   * - May be the same as current node if no transition occurred
   */
  next: string | undefined;

  /**
   * Optional flag indicating whether the conversation has completed.
   * When `true`, the conversation has reached a terminal node and
   * no further processing should occur.
   */
  done?: boolean;
};
